name: KDT CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh
          echo "KONDUKTO_HOST=https://konduktolab.kondukto.local" >> $GITHUB_ENV
          echo "KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}" >> $GITHUB_ENV  # Using GitHub Secrets

      - name: Run a CS scan
        env:
          KONDUKTO_TOKEN: ${{ secrets.KONDUKTO_TOKEN }}  # Using GitHub Secrets
        run: |
          kdt scan \
            --host https://konduktolab.kondukto.local \
            --token bzVpdUpqZ1V5WldlYlI2WFZtaDNrVjl4eWZFMFdmYmg5TWxMTkJuSjAzQ1duVmJabVVUZDhqMllUdERm \
            -p KaiMonkey \
            -t checkov \
            --image=ubuntu:latest \
            -b master \
            --insecure \
            --output results.json  # Save results in JSON format

      - name: Import results to Kondukto
        env:
          KONDUKTO_TOKEN: ${{ secrets.KONDUKTO_TOKEN }}  # Using GitHub Secrets
        run: |
          kdt import \
            --host https://konduktolab.kondukto.local \
            --token bzVpdUpqZ1V5WldlYlI2WFZtaDNrVjl4eWZFMFdmYmg5TWxMTkJuSjAzQ1duVmJabVVUZDhqMllUdERm \
            -p KaiMonkey \
            -t checkov \
            --file results.json
